create table if not exists public.cf_handles (
  handle_key text primary key,
  handle text not null,
  rank text,
  rating integer,
  max_rank text,
  max_rating integer,
  contribution integer,
  friend_of_count integer,
  title_photo text,
  last_info_refresh_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cf_contests (
  contest_id integer primary key,
  name text not null,
  kind text not null default 'official',
  division text,
  phase text,
  duration_seconds integer,
  start_time_seconds integer,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cf_handle_rating_history (
  handle_key text not null,
  handle text not null,
  contest_id integer not null references public.cf_contests(contest_id) on delete cascade,
  contest_name text not null,
  rank integer,
  old_rating integer,
  new_rating integer,
  rating_update_time_seconds integer,
  history_index integer,
  refreshed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (handle_key, contest_id)
);

create index if not exists cf_handle_rating_history_contest_idx
  on public.cf_handle_rating_history (contest_id);

create table if not exists public.cf_performance_estimates (
  handle_key text not null,
  handle text not null,
  contest_id integer not null references public.cf_contests(contest_id) on delete cascade,
  formula_version integer not null,
  performance integer,
  rank integer,
  participant_count integer,
  old_rating integer,
  new_rating integer,
  rating_delta integer,
  contest_name text not null,
  rating_update_time_seconds integer,
  computed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (handle_key, contest_id, formula_version)
);

create index if not exists cf_performance_estimates_contest_idx
  on public.cf_performance_estimates (contest_id, formula_version);

create table if not exists public.cf_touched_contests (
  handle_key text not null,
  handle text not null,
  contest_id integer not null,
  source text not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (handle_key, contest_id, source)
);

create table if not exists public.cf_friend_handles (
  owner_handle text not null,
  owner_handle_key text not null,
  friend_handle text not null,
  friend_handle_key text not null,
  source text not null,
  last_seen_at timestamptz not null default now(),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (owner_handle_key, friend_handle_key)
);

create table if not exists public.cf_cache_warm_queue (
  id bigserial primary key,
  task_key text not null unique,
  task_type text not null,
  payload jsonb not null default '{}'::jsonb,
  priority integer not null default 100,
  run_after timestamptz not null default now(),
  attempts integer not null default 0,
  locked_at timestamptz,
  done_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cf_cache_warm_queue_ready_idx
  on public.cf_cache_warm_queue (done_at, run_after, priority, id);

alter table public.cf_handles enable row level security;
alter table public.cf_contests enable row level security;
alter table public.cf_handle_rating_history enable row level security;
alter table public.cf_performance_estimates enable row level security;
alter table public.cf_touched_contests enable row level security;
alter table public.cf_friend_handles enable row level security;
alter table public.cf_cache_warm_queue enable row level security;

grant select, insert, update, delete on table public.cf_handles to service_role;
grant select, insert, update, delete on table public.cf_contests to service_role;
grant select, insert, update, delete on table public.cf_handle_rating_history to service_role;
grant select, insert, update, delete on table public.cf_performance_estimates to service_role;
grant select, insert, update, delete on table public.cf_touched_contests to service_role;
grant select, insert, update, delete on table public.cf_friend_handles to service_role;
grant select, insert, update, delete on table public.cf_cache_warm_queue to service_role;
grant usage, select on sequence public.cf_cache_warm_queue_id_seq to service_role;

create or replace function public.enqueue_cf_cache_warm_task(
  p_task_key text,
  p_task_type text,
  p_payload jsonb default '{}'::jsonb,
  p_priority integer default 100,
  p_run_after timestamptz default now()
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.cf_cache_warm_queue (
    task_key,
    task_type,
    payload,
    priority,
    run_after,
    done_at,
    locked_at,
    attempts,
    last_error,
    updated_at
  )
  values (
    p_task_key,
    p_task_type,
    coalesce(p_payload, '{}'::jsonb),
    p_priority,
    p_run_after,
    null,
    null,
    0,
    null,
    now()
  )
  on conflict (task_key) do update set
    task_type = excluded.task_type,
    payload = excluded.payload,
    priority = least(public.cf_cache_warm_queue.priority, excluded.priority),
    run_after = least(public.cf_cache_warm_queue.run_after, excluded.run_after),
    done_at = null,
    locked_at = null,
    last_error = null,
    updated_at = now();
end;
$$;

grant execute on function public.enqueue_cf_cache_warm_task(text, text, jsonb, integer, timestamptz) to service_role;

insert into public.cf_friend_handles (
  owner_handle,
  owner_handle_key,
  friend_handle,
  friend_handle_key,
  source,
  last_seen_at,
  active
)
values
    ('octane', lower('octane'), 'kcm1700', lower('kcm1700'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'ainta', lower('ainta'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'xtalclr', lower('xtalclr'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Konijntje', lower('Konijntje'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Hyperbolic', lower('Hyperbolic'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'ko_osaga', lower('ko_osaga'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Bubbler', lower('Bubbler'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'GyojunYoun', lower('GyojunYoun'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'sean617', lower('sean617'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Abra_Stone', lower('Abra_Stone'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), '79brue', lower('79brue'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Jhuni', lower('Jhuni'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Ryute', lower('Ryute'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Onjo', lower('Onjo'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'pizzaroot', lower('pizzaroot'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'YeongTree', lower('YeongTree'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'SongC', lower('SongC'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'jo_on', lower('jo_on'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'andy627', lower('andy627'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'leejseo', lower('leejseo'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Eunha', lower('Eunha'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'denniskim', lower('denniskim'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'imeimi', lower('imeimi'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'shiftpsh', lower('shiftpsh'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'djm03178', lower('djm03178'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'parkky', lower('parkky'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'leo020630', lower('leo020630'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Serin', lower('Serin'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Worteltje', lower('Worteltje'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Lawali', lower('Lawali'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'cgiosy0', lower('cgiosy0'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'kizen', lower('kizen'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'donghoony', lower('donghoony'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'DDUDUDDUDU', lower('DDUDUDDUDU'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'mjhmjh1104', lower('mjhmjh1104'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), '055D', lower('055D'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'dillon0108', lower('dillon0108'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'garam1732', lower('garam1732'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'grace0068', lower('grace0068'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Justice_Hui', lower('Justice_Hui'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'est_stella', lower('est_stella'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'RedundantCarrots', lower('RedundantCarrots'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'kiwiyou', lower('kiwiyou'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), '24014653', lower('24014653'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'whqkrkt04', lower('whqkrkt04'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'azberjibiou', lower('azberjibiou'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'IZONE', lower('IZONE'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'khuepr123', lower('khuepr123'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'EN_SA', lower('EN_SA'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'LLM', lower('LLM'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'yooyou7', lower('yooyou7'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Little_Bunny', lower('Little_Bunny'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'jjang36524', lower('jjang36524'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'hibye1217', lower('hibye1217'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'platter', lower('platter'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), '_CgnoS_', lower('_CgnoS_'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'gunwo_okim', lower('gunwo_okim'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'man_of_learning', lower('man_of_learning'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'BiouX', lower('BiouX'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'jaewoo2009', lower('jaewoo2009'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'nlog', lower('nlog'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'gs20036', lower('gs20036'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'codingmorning', lower('codingmorning'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'sedev57', lower('sedev57'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'borussiam', lower('borussiam'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'kclee2172', lower('kclee2172'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'leinad2', lower('leinad2'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'JYJin', lower('JYJin'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'lemoncookie', lower('lemoncookie'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'kchwoony210', lower('kchwoony210'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'wheoeld04', lower('wheoeld04'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'papergundam', lower('papergundam'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Physics07', lower('Physics07'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'qwerasdfzxcl', lower('qwerasdfzxcl'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'amsminn', lower('amsminn'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Shirakami_Fubuki', lower('Shirakami_Fubuki'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'namolbbaemi', lower('namolbbaemi'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'nahida', lower('nahida'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'lumine_scence', lower('lumine_scence'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'haru_101', lower('haru_101'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'middle_man', lower('middle_man'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'juneharold', lower('juneharold'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'alex0211', lower('alex0211'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'chelate1118', lower('chelate1118'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Serendipity__', lower('Serendipity__'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'pianory', lower('pianory'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'deltarune', lower('deltarune'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'IBory', lower('IBory'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'dongwondavid', lower('dongwondavid'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'IndexLP', lower('IndexLP'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'meow_love', lower('meow_love'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'imtore', lower('imtore'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'dissolve314', lower('dissolve314'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'RussianBlue', lower('RussianBlue'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'crescmoon', lower('crescmoon'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'chaeyihwan', lower('chaeyihwan'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'gs21044', lower('gs21044'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'kenji_koiso', lower('kenji_koiso'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'ComPhyPark', lower('ComPhyPark'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Senoia17', lower('Senoia17'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'windva', lower('windva'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'andyandy', lower('andyandy'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'RyuZU', lower('RyuZU'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'dayodayo', lower('dayodayo'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Cross_Ratio', lower('Cross_Ratio'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Shadowdle', lower('Shadowdle'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Ashen-Witch', lower('Ashen-Witch'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'BLACKPINK', lower('BLACKPINK'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'alsrjs0725', lower('alsrjs0725'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'JaewonOh', lower('JaewonOh'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'SCH314', lower('SCH314'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'aaronkim00', lower('aaronkim00'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'ssamt', lower('ssamt'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'hanbyeol_', lower('hanbyeol_'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'ez_code', lower('ez_code'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'ai4youej', lower('ai4youej'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'wizardrabbit', lower('wizardrabbit'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'mz_en', lower('mz_en'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Numbering', lower('Numbering'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'riroan', lower('riroan'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'sorohue', lower('sorohue'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'chromate00', lower('chromate00'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'soongsil', lower('soongsil'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'terrasphere', lower('terrasphere'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'minpaper', lower('minpaper'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Kleder', lower('Kleder'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'mythofys', lower('mythofys'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Shinonome_Ena', lower('Shinonome_Ena'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'junah', lower('junah'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Kaling', lower('Kaling'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'johnny8337', lower('johnny8337'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'taeyun149', lower('taeyun149'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Equinox_', lower('Equinox_'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'josephan8375', lower('josephan8375'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Starbow_Break', lower('Starbow_Break'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'annyeong1', lower('annyeong1'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'guroy', lower('guroy'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'iccodly', lower('iccodly'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'sshs22002', lower('sshs22002'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'junha1282', lower('junha1282'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'uuiip7878', lower('uuiip7878'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'eltu815', lower('eltu815'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'awwkje', lower('awwkje'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'MagicShow', lower('MagicShow'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'mbae059', lower('mbae059'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), '21007', lower('21007'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'aaat', lower('aaat'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'honeykill', lower('honeykill'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Mingyu331', lower('Mingyu331'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Saturnalorbit', lower('Saturnalorbit'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'easteregg423', lower('easteregg423'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'sshseddie', lower('sshseddie'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'utilforever', lower('utilforever'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'kongum', lower('kongum'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'now_cow', lower('now_cow'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'junhyung9985', lower('junhyung9985'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'mickeyjung', lower('mickeyjung'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Faruzan', lower('Faruzan'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'ogura_yui', lower('ogura_yui'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'w8385', lower('w8385'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'kaorin', lower('kaorin'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'linzy_thanatos', lower('linzy_thanatos'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'nflight11', lower('nflight11'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'cygnus_330', lower('cygnus_330'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'sjh1224', lower('sjh1224'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'blackkarn', lower('blackkarn'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'invrtd.h', lower('invrtd.h'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Schur', lower('Schur'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'iktk', lower('iktk'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'cologne1723', lower('cologne1723'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'chiyo_shock', lower('chiyo_shock'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'toycartoon', lower('toycartoon'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'iacobus', lower('iacobus'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'prettychang', lower('prettychang'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'UNDERTAKER', lower('UNDERTAKER'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'woohyun_jng', lower('woohyun_jng'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'synthes1s', lower('synthes1s'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'kdy8128', lower('kdy8128'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'khf7000', lower('khf7000'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'angeliayam', lower('angeliayam'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'hello107', lower('hello107'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'lemonoyaa', lower('lemonoyaa'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'bsh1004', lower('bsh1004'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'kohada', lower('kohada'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'iluem100', lower('iluem100'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'kolorVXL', lower('kolorVXL'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'cywohoy', lower('cywohoy'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'seer_of_c', lower('seer_of_c'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'sb_p_0x7', lower('sb_p_0x7'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'notkim16', lower('notkim16'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Hakuaa_2', lower('Hakuaa_2'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'lumitt', lower('lumitt'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'Cenix820', lower('Cenix820'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), '_______________________', lower('_______________________'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'cy4n1de', lower('cy4n1de'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'kokiri', lower('kokiri'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'kulkuri', lower('kulkuri'), 'pasted_codeforces_friends', now(), true),
    ('octane', lower('octane'), 'qwertyuiojhygtfdfg', lower('qwertyuiojhygtfdfg'), 'pasted_codeforces_friends', now(), true)
on conflict (owner_handle_key, friend_handle_key) do update set
  friend_handle = excluded.friend_handle,
  source = excluded.source,
  last_seen_at = excluded.last_seen_at,
  active = true,
  updated_at = now();

insert into public.cf_cache_warm_queue (task_key, task_type, payload, priority, run_after)
values
    ('contest-list:official', 'contest-list', jsonb_build_object('gym', false), 10, now()),
    ('contest-list:gym', 'contest-list', jsonb_build_object('gym', true), 15, now()),
    ('handle-info:octane', 'handle-info', jsonb_build_object('handle', 'octane'), 18, now()),
    ('handle-rating:octane', 'handle-rating', jsonb_build_object('handle', 'octane'), 28, now()),
    ('handle-info:kcm1700', 'handle-info', jsonb_build_object('handle', 'kcm1700'), 20, now()),
    ('handle-rating:kcm1700', 'handle-rating', jsonb_build_object('handle', 'kcm1700'), 30, now()),
    ('handle-info:ainta', 'handle-info', jsonb_build_object('handle', 'ainta'), 20, now()),
    ('handle-rating:ainta', 'handle-rating', jsonb_build_object('handle', 'ainta'), 30, now()),
    ('handle-info:xtalclr', 'handle-info', jsonb_build_object('handle', 'xtalclr'), 20, now()),
    ('handle-rating:xtalclr', 'handle-rating', jsonb_build_object('handle', 'xtalclr'), 30, now()),
    ('handle-info:konijntje', 'handle-info', jsonb_build_object('handle', 'Konijntje'), 20, now()),
    ('handle-rating:konijntje', 'handle-rating', jsonb_build_object('handle', 'Konijntje'), 30, now()),
    ('handle-info:hyperbolic', 'handle-info', jsonb_build_object('handle', 'Hyperbolic'), 20, now()),
    ('handle-rating:hyperbolic', 'handle-rating', jsonb_build_object('handle', 'Hyperbolic'), 30, now()),
    ('handle-info:ko_osaga', 'handle-info', jsonb_build_object('handle', 'ko_osaga'), 20, now()),
    ('handle-rating:ko_osaga', 'handle-rating', jsonb_build_object('handle', 'ko_osaga'), 30, now()),
    ('handle-info:bubbler', 'handle-info', jsonb_build_object('handle', 'Bubbler'), 20, now()),
    ('handle-rating:bubbler', 'handle-rating', jsonb_build_object('handle', 'Bubbler'), 30, now()),
    ('handle-info:gyojunyoun', 'handle-info', jsonb_build_object('handle', 'GyojunYoun'), 20, now()),
    ('handle-rating:gyojunyoun', 'handle-rating', jsonb_build_object('handle', 'GyojunYoun'), 30, now()),
    ('handle-info:sean617', 'handle-info', jsonb_build_object('handle', 'sean617'), 20, now()),
    ('handle-rating:sean617', 'handle-rating', jsonb_build_object('handle', 'sean617'), 30, now()),
    ('handle-info:abra_stone', 'handle-info', jsonb_build_object('handle', 'Abra_Stone'), 20, now()),
    ('handle-rating:abra_stone', 'handle-rating', jsonb_build_object('handle', 'Abra_Stone'), 30, now()),
    ('handle-info:79brue', 'handle-info', jsonb_build_object('handle', '79brue'), 20, now()),
    ('handle-rating:79brue', 'handle-rating', jsonb_build_object('handle', '79brue'), 30, now()),
    ('handle-info:jhuni', 'handle-info', jsonb_build_object('handle', 'Jhuni'), 20, now()),
    ('handle-rating:jhuni', 'handle-rating', jsonb_build_object('handle', 'Jhuni'), 30, now()),
    ('handle-info:ryute', 'handle-info', jsonb_build_object('handle', 'Ryute'), 20, now()),
    ('handle-rating:ryute', 'handle-rating', jsonb_build_object('handle', 'Ryute'), 30, now()),
    ('handle-info:onjo', 'handle-info', jsonb_build_object('handle', 'Onjo'), 20, now()),
    ('handle-rating:onjo', 'handle-rating', jsonb_build_object('handle', 'Onjo'), 30, now()),
    ('handle-info:pizzaroot', 'handle-info', jsonb_build_object('handle', 'pizzaroot'), 20, now()),
    ('handle-rating:pizzaroot', 'handle-rating', jsonb_build_object('handle', 'pizzaroot'), 30, now()),
    ('handle-info:yeongtree', 'handle-info', jsonb_build_object('handle', 'YeongTree'), 20, now()),
    ('handle-rating:yeongtree', 'handle-rating', jsonb_build_object('handle', 'YeongTree'), 30, now()),
    ('handle-info:songc', 'handle-info', jsonb_build_object('handle', 'SongC'), 20, now()),
    ('handle-rating:songc', 'handle-rating', jsonb_build_object('handle', 'SongC'), 30, now()),
    ('handle-info:jo_on', 'handle-info', jsonb_build_object('handle', 'jo_on'), 20, now()),
    ('handle-rating:jo_on', 'handle-rating', jsonb_build_object('handle', 'jo_on'), 30, now()),
    ('handle-info:andy627', 'handle-info', jsonb_build_object('handle', 'andy627'), 20, now()),
    ('handle-rating:andy627', 'handle-rating', jsonb_build_object('handle', 'andy627'), 30, now()),
    ('handle-info:leejseo', 'handle-info', jsonb_build_object('handle', 'leejseo'), 20, now()),
    ('handle-rating:leejseo', 'handle-rating', jsonb_build_object('handle', 'leejseo'), 30, now()),
    ('handle-info:eunha', 'handle-info', jsonb_build_object('handle', 'Eunha'), 20, now()),
    ('handle-rating:eunha', 'handle-rating', jsonb_build_object('handle', 'Eunha'), 30, now()),
    ('handle-info:denniskim', 'handle-info', jsonb_build_object('handle', 'denniskim'), 20, now()),
    ('handle-rating:denniskim', 'handle-rating', jsonb_build_object('handle', 'denniskim'), 30, now()),
    ('handle-info:imeimi', 'handle-info', jsonb_build_object('handle', 'imeimi'), 20, now()),
    ('handle-rating:imeimi', 'handle-rating', jsonb_build_object('handle', 'imeimi'), 30, now()),
    ('handle-info:shiftpsh', 'handle-info', jsonb_build_object('handle', 'shiftpsh'), 20, now()),
    ('handle-rating:shiftpsh', 'handle-rating', jsonb_build_object('handle', 'shiftpsh'), 30, now()),
    ('handle-info:djm03178', 'handle-info', jsonb_build_object('handle', 'djm03178'), 20, now()),
    ('handle-rating:djm03178', 'handle-rating', jsonb_build_object('handle', 'djm03178'), 30, now()),
    ('handle-info:parkky', 'handle-info', jsonb_build_object('handle', 'parkky'), 20, now()),
    ('handle-rating:parkky', 'handle-rating', jsonb_build_object('handle', 'parkky'), 30, now()),
    ('handle-info:leo020630', 'handle-info', jsonb_build_object('handle', 'leo020630'), 20, now()),
    ('handle-rating:leo020630', 'handle-rating', jsonb_build_object('handle', 'leo020630'), 30, now()),
    ('handle-info:serin', 'handle-info', jsonb_build_object('handle', 'Serin'), 20, now()),
    ('handle-rating:serin', 'handle-rating', jsonb_build_object('handle', 'Serin'), 30, now()),
    ('handle-info:worteltje', 'handle-info', jsonb_build_object('handle', 'Worteltje'), 20, now()),
    ('handle-rating:worteltje', 'handle-rating', jsonb_build_object('handle', 'Worteltje'), 30, now()),
    ('handle-info:lawali', 'handle-info', jsonb_build_object('handle', 'Lawali'), 20, now()),
    ('handle-rating:lawali', 'handle-rating', jsonb_build_object('handle', 'Lawali'), 30, now()),
    ('handle-info:cgiosy0', 'handle-info', jsonb_build_object('handle', 'cgiosy0'), 20, now()),
    ('handle-rating:cgiosy0', 'handle-rating', jsonb_build_object('handle', 'cgiosy0'), 30, now()),
    ('handle-info:kizen', 'handle-info', jsonb_build_object('handle', 'kizen'), 20, now()),
    ('handle-rating:kizen', 'handle-rating', jsonb_build_object('handle', 'kizen'), 30, now()),
    ('handle-info:donghoony', 'handle-info', jsonb_build_object('handle', 'donghoony'), 20, now()),
    ('handle-rating:donghoony', 'handle-rating', jsonb_build_object('handle', 'donghoony'), 30, now()),
    ('handle-info:ddududdudu', 'handle-info', jsonb_build_object('handle', 'DDUDUDDUDU'), 20, now()),
    ('handle-rating:ddududdudu', 'handle-rating', jsonb_build_object('handle', 'DDUDUDDUDU'), 30, now()),
    ('handle-info:mjhmjh1104', 'handle-info', jsonb_build_object('handle', 'mjhmjh1104'), 20, now()),
    ('handle-rating:mjhmjh1104', 'handle-rating', jsonb_build_object('handle', 'mjhmjh1104'), 30, now()),
    ('handle-info:055d', 'handle-info', jsonb_build_object('handle', '055D'), 20, now()),
    ('handle-rating:055d', 'handle-rating', jsonb_build_object('handle', '055D'), 30, now()),
    ('handle-info:dillon0108', 'handle-info', jsonb_build_object('handle', 'dillon0108'), 20, now()),
    ('handle-rating:dillon0108', 'handle-rating', jsonb_build_object('handle', 'dillon0108'), 30, now()),
    ('handle-info:garam1732', 'handle-info', jsonb_build_object('handle', 'garam1732'), 20, now()),
    ('handle-rating:garam1732', 'handle-rating', jsonb_build_object('handle', 'garam1732'), 30, now()),
    ('handle-info:grace0068', 'handle-info', jsonb_build_object('handle', 'grace0068'), 20, now()),
    ('handle-rating:grace0068', 'handle-rating', jsonb_build_object('handle', 'grace0068'), 30, now()),
    ('handle-info:justice_hui', 'handle-info', jsonb_build_object('handle', 'Justice_Hui'), 20, now()),
    ('handle-rating:justice_hui', 'handle-rating', jsonb_build_object('handle', 'Justice_Hui'), 30, now()),
    ('handle-info:est_stella', 'handle-info', jsonb_build_object('handle', 'est_stella'), 20, now()),
    ('handle-rating:est_stella', 'handle-rating', jsonb_build_object('handle', 'est_stella'), 30, now()),
    ('handle-info:redundantcarrots', 'handle-info', jsonb_build_object('handle', 'RedundantCarrots'), 20, now()),
    ('handle-rating:redundantcarrots', 'handle-rating', jsonb_build_object('handle', 'RedundantCarrots'), 30, now()),
    ('handle-info:kiwiyou', 'handle-info', jsonb_build_object('handle', 'kiwiyou'), 20, now()),
    ('handle-rating:kiwiyou', 'handle-rating', jsonb_build_object('handle', 'kiwiyou'), 30, now()),
    ('handle-info:24014653', 'handle-info', jsonb_build_object('handle', '24014653'), 20, now()),
    ('handle-rating:24014653', 'handle-rating', jsonb_build_object('handle', '24014653'), 30, now()),
    ('handle-info:whqkrkt04', 'handle-info', jsonb_build_object('handle', 'whqkrkt04'), 20, now()),
    ('handle-rating:whqkrkt04', 'handle-rating', jsonb_build_object('handle', 'whqkrkt04'), 30, now()),
    ('handle-info:azberjibiou', 'handle-info', jsonb_build_object('handle', 'azberjibiou'), 20, now()),
    ('handle-rating:azberjibiou', 'handle-rating', jsonb_build_object('handle', 'azberjibiou'), 30, now()),
    ('handle-info:izone', 'handle-info', jsonb_build_object('handle', 'IZONE'), 20, now()),
    ('handle-rating:izone', 'handle-rating', jsonb_build_object('handle', 'IZONE'), 30, now()),
    ('handle-info:khuepr123', 'handle-info', jsonb_build_object('handle', 'khuepr123'), 20, now()),
    ('handle-rating:khuepr123', 'handle-rating', jsonb_build_object('handle', 'khuepr123'), 30, now()),
    ('handle-info:en_sa', 'handle-info', jsonb_build_object('handle', 'EN_SA'), 20, now()),
    ('handle-rating:en_sa', 'handle-rating', jsonb_build_object('handle', 'EN_SA'), 30, now()),
    ('handle-info:llm', 'handle-info', jsonb_build_object('handle', 'LLM'), 20, now()),
    ('handle-rating:llm', 'handle-rating', jsonb_build_object('handle', 'LLM'), 30, now()),
    ('handle-info:yooyou7', 'handle-info', jsonb_build_object('handle', 'yooyou7'), 20, now()),
    ('handle-rating:yooyou7', 'handle-rating', jsonb_build_object('handle', 'yooyou7'), 30, now()),
    ('handle-info:little_bunny', 'handle-info', jsonb_build_object('handle', 'Little_Bunny'), 20, now()),
    ('handle-rating:little_bunny', 'handle-rating', jsonb_build_object('handle', 'Little_Bunny'), 30, now()),
    ('handle-info:jjang36524', 'handle-info', jsonb_build_object('handle', 'jjang36524'), 20, now()),
    ('handle-rating:jjang36524', 'handle-rating', jsonb_build_object('handle', 'jjang36524'), 30, now()),
    ('handle-info:hibye1217', 'handle-info', jsonb_build_object('handle', 'hibye1217'), 20, now()),
    ('handle-rating:hibye1217', 'handle-rating', jsonb_build_object('handle', 'hibye1217'), 30, now()),
    ('handle-info:platter', 'handle-info', jsonb_build_object('handle', 'platter'), 20, now()),
    ('handle-rating:platter', 'handle-rating', jsonb_build_object('handle', 'platter'), 30, now()),
    ('handle-info:_cgnos_', 'handle-info', jsonb_build_object('handle', '_CgnoS_'), 20, now()),
    ('handle-rating:_cgnos_', 'handle-rating', jsonb_build_object('handle', '_CgnoS_'), 30, now()),
    ('handle-info:gunwo_okim', 'handle-info', jsonb_build_object('handle', 'gunwo_okim'), 20, now()),
    ('handle-rating:gunwo_okim', 'handle-rating', jsonb_build_object('handle', 'gunwo_okim'), 30, now()),
    ('handle-info:man_of_learning', 'handle-info', jsonb_build_object('handle', 'man_of_learning'), 20, now()),
    ('handle-rating:man_of_learning', 'handle-rating', jsonb_build_object('handle', 'man_of_learning'), 30, now()),
    ('handle-info:bioux', 'handle-info', jsonb_build_object('handle', 'BiouX'), 20, now()),
    ('handle-rating:bioux', 'handle-rating', jsonb_build_object('handle', 'BiouX'), 30, now()),
    ('handle-info:jaewoo2009', 'handle-info', jsonb_build_object('handle', 'jaewoo2009'), 20, now()),
    ('handle-rating:jaewoo2009', 'handle-rating', jsonb_build_object('handle', 'jaewoo2009'), 30, now()),
    ('handle-info:nlog', 'handle-info', jsonb_build_object('handle', 'nlog'), 20, now()),
    ('handle-rating:nlog', 'handle-rating', jsonb_build_object('handle', 'nlog'), 30, now()),
    ('handle-info:gs20036', 'handle-info', jsonb_build_object('handle', 'gs20036'), 20, now()),
    ('handle-rating:gs20036', 'handle-rating', jsonb_build_object('handle', 'gs20036'), 30, now()),
    ('handle-info:codingmorning', 'handle-info', jsonb_build_object('handle', 'codingmorning'), 20, now()),
    ('handle-rating:codingmorning', 'handle-rating', jsonb_build_object('handle', 'codingmorning'), 30, now()),
    ('handle-info:sedev57', 'handle-info', jsonb_build_object('handle', 'sedev57'), 20, now()),
    ('handle-rating:sedev57', 'handle-rating', jsonb_build_object('handle', 'sedev57'), 30, now()),
    ('handle-info:borussiam', 'handle-info', jsonb_build_object('handle', 'borussiam'), 20, now()),
    ('handle-rating:borussiam', 'handle-rating', jsonb_build_object('handle', 'borussiam'), 30, now()),
    ('handle-info:kclee2172', 'handle-info', jsonb_build_object('handle', 'kclee2172'), 20, now()),
    ('handle-rating:kclee2172', 'handle-rating', jsonb_build_object('handle', 'kclee2172'), 30, now()),
    ('handle-info:leinad2', 'handle-info', jsonb_build_object('handle', 'leinad2'), 20, now()),
    ('handle-rating:leinad2', 'handle-rating', jsonb_build_object('handle', 'leinad2'), 30, now()),
    ('handle-info:jyjin', 'handle-info', jsonb_build_object('handle', 'JYJin'), 20, now()),
    ('handle-rating:jyjin', 'handle-rating', jsonb_build_object('handle', 'JYJin'), 30, now()),
    ('handle-info:lemoncookie', 'handle-info', jsonb_build_object('handle', 'lemoncookie'), 20, now()),
    ('handle-rating:lemoncookie', 'handle-rating', jsonb_build_object('handle', 'lemoncookie'), 30, now()),
    ('handle-info:kchwoony210', 'handle-info', jsonb_build_object('handle', 'kchwoony210'), 20, now()),
    ('handle-rating:kchwoony210', 'handle-rating', jsonb_build_object('handle', 'kchwoony210'), 30, now()),
    ('handle-info:wheoeld04', 'handle-info', jsonb_build_object('handle', 'wheoeld04'), 20, now()),
    ('handle-rating:wheoeld04', 'handle-rating', jsonb_build_object('handle', 'wheoeld04'), 30, now()),
    ('handle-info:papergundam', 'handle-info', jsonb_build_object('handle', 'papergundam'), 20, now()),
    ('handle-rating:papergundam', 'handle-rating', jsonb_build_object('handle', 'papergundam'), 30, now()),
    ('handle-info:physics07', 'handle-info', jsonb_build_object('handle', 'Physics07'), 20, now()),
    ('handle-rating:physics07', 'handle-rating', jsonb_build_object('handle', 'Physics07'), 30, now()),
    ('handle-info:qwerasdfzxcl', 'handle-info', jsonb_build_object('handle', 'qwerasdfzxcl'), 20, now()),
    ('handle-rating:qwerasdfzxcl', 'handle-rating', jsonb_build_object('handle', 'qwerasdfzxcl'), 30, now()),
    ('handle-info:amsminn', 'handle-info', jsonb_build_object('handle', 'amsminn'), 20, now()),
    ('handle-rating:amsminn', 'handle-rating', jsonb_build_object('handle', 'amsminn'), 30, now()),
    ('handle-info:shirakami_fubuki', 'handle-info', jsonb_build_object('handle', 'Shirakami_Fubuki'), 20, now()),
    ('handle-rating:shirakami_fubuki', 'handle-rating', jsonb_build_object('handle', 'Shirakami_Fubuki'), 30, now()),
    ('handle-info:namolbbaemi', 'handle-info', jsonb_build_object('handle', 'namolbbaemi'), 20, now()),
    ('handle-rating:namolbbaemi', 'handle-rating', jsonb_build_object('handle', 'namolbbaemi'), 30, now()),
    ('handle-info:nahida', 'handle-info', jsonb_build_object('handle', 'nahida'), 20, now()),
    ('handle-rating:nahida', 'handle-rating', jsonb_build_object('handle', 'nahida'), 30, now()),
    ('handle-info:lumine_scence', 'handle-info', jsonb_build_object('handle', 'lumine_scence'), 20, now()),
    ('handle-rating:lumine_scence', 'handle-rating', jsonb_build_object('handle', 'lumine_scence'), 30, now()),
    ('handle-info:haru_101', 'handle-info', jsonb_build_object('handle', 'haru_101'), 20, now()),
    ('handle-rating:haru_101', 'handle-rating', jsonb_build_object('handle', 'haru_101'), 30, now()),
    ('handle-info:middle_man', 'handle-info', jsonb_build_object('handle', 'middle_man'), 20, now()),
    ('handle-rating:middle_man', 'handle-rating', jsonb_build_object('handle', 'middle_man'), 30, now()),
    ('handle-info:juneharold', 'handle-info', jsonb_build_object('handle', 'juneharold'), 20, now()),
    ('handle-rating:juneharold', 'handle-rating', jsonb_build_object('handle', 'juneharold'), 30, now()),
    ('handle-info:alex0211', 'handle-info', jsonb_build_object('handle', 'alex0211'), 20, now()),
    ('handle-rating:alex0211', 'handle-rating', jsonb_build_object('handle', 'alex0211'), 30, now()),
    ('handle-info:chelate1118', 'handle-info', jsonb_build_object('handle', 'chelate1118'), 20, now()),
    ('handle-rating:chelate1118', 'handle-rating', jsonb_build_object('handle', 'chelate1118'), 30, now()),
    ('handle-info:serendipity__', 'handle-info', jsonb_build_object('handle', 'Serendipity__'), 20, now()),
    ('handle-rating:serendipity__', 'handle-rating', jsonb_build_object('handle', 'Serendipity__'), 30, now()),
    ('handle-info:pianory', 'handle-info', jsonb_build_object('handle', 'pianory'), 20, now()),
    ('handle-rating:pianory', 'handle-rating', jsonb_build_object('handle', 'pianory'), 30, now()),
    ('handle-info:deltarune', 'handle-info', jsonb_build_object('handle', 'deltarune'), 20, now()),
    ('handle-rating:deltarune', 'handle-rating', jsonb_build_object('handle', 'deltarune'), 30, now()),
    ('handle-info:ibory', 'handle-info', jsonb_build_object('handle', 'IBory'), 20, now()),
    ('handle-rating:ibory', 'handle-rating', jsonb_build_object('handle', 'IBory'), 30, now()),
    ('handle-info:dongwondavid', 'handle-info', jsonb_build_object('handle', 'dongwondavid'), 20, now()),
    ('handle-rating:dongwondavid', 'handle-rating', jsonb_build_object('handle', 'dongwondavid'), 30, now()),
    ('handle-info:indexlp', 'handle-info', jsonb_build_object('handle', 'IndexLP'), 20, now()),
    ('handle-rating:indexlp', 'handle-rating', jsonb_build_object('handle', 'IndexLP'), 30, now()),
    ('handle-info:meow_love', 'handle-info', jsonb_build_object('handle', 'meow_love'), 20, now()),
    ('handle-rating:meow_love', 'handle-rating', jsonb_build_object('handle', 'meow_love'), 30, now()),
    ('handle-info:imtore', 'handle-info', jsonb_build_object('handle', 'imtore'), 20, now()),
    ('handle-rating:imtore', 'handle-rating', jsonb_build_object('handle', 'imtore'), 30, now()),
    ('handle-info:dissolve314', 'handle-info', jsonb_build_object('handle', 'dissolve314'), 20, now()),
    ('handle-rating:dissolve314', 'handle-rating', jsonb_build_object('handle', 'dissolve314'), 30, now()),
    ('handle-info:russianblue', 'handle-info', jsonb_build_object('handle', 'RussianBlue'), 20, now()),
    ('handle-rating:russianblue', 'handle-rating', jsonb_build_object('handle', 'RussianBlue'), 30, now()),
    ('handle-info:crescmoon', 'handle-info', jsonb_build_object('handle', 'crescmoon'), 20, now()),
    ('handle-rating:crescmoon', 'handle-rating', jsonb_build_object('handle', 'crescmoon'), 30, now()),
    ('handle-info:chaeyihwan', 'handle-info', jsonb_build_object('handle', 'chaeyihwan'), 20, now()),
    ('handle-rating:chaeyihwan', 'handle-rating', jsonb_build_object('handle', 'chaeyihwan'), 30, now()),
    ('handle-info:gs21044', 'handle-info', jsonb_build_object('handle', 'gs21044'), 20, now()),
    ('handle-rating:gs21044', 'handle-rating', jsonb_build_object('handle', 'gs21044'), 30, now()),
    ('handle-info:kenji_koiso', 'handle-info', jsonb_build_object('handle', 'kenji_koiso'), 20, now()),
    ('handle-rating:kenji_koiso', 'handle-rating', jsonb_build_object('handle', 'kenji_koiso'), 30, now()),
    ('handle-info:comphypark', 'handle-info', jsonb_build_object('handle', 'ComPhyPark'), 20, now()),
    ('handle-rating:comphypark', 'handle-rating', jsonb_build_object('handle', 'ComPhyPark'), 30, now()),
    ('handle-info:senoia17', 'handle-info', jsonb_build_object('handle', 'Senoia17'), 20, now()),
    ('handle-rating:senoia17', 'handle-rating', jsonb_build_object('handle', 'Senoia17'), 30, now()),
    ('handle-info:windva', 'handle-info', jsonb_build_object('handle', 'windva'), 20, now()),
    ('handle-rating:windva', 'handle-rating', jsonb_build_object('handle', 'windva'), 30, now()),
    ('handle-info:andyandy', 'handle-info', jsonb_build_object('handle', 'andyandy'), 20, now()),
    ('handle-rating:andyandy', 'handle-rating', jsonb_build_object('handle', 'andyandy'), 30, now()),
    ('handle-info:ryuzu', 'handle-info', jsonb_build_object('handle', 'RyuZU'), 20, now()),
    ('handle-rating:ryuzu', 'handle-rating', jsonb_build_object('handle', 'RyuZU'), 30, now()),
    ('handle-info:dayodayo', 'handle-info', jsonb_build_object('handle', 'dayodayo'), 20, now()),
    ('handle-rating:dayodayo', 'handle-rating', jsonb_build_object('handle', 'dayodayo'), 30, now()),
    ('handle-info:cross_ratio', 'handle-info', jsonb_build_object('handle', 'Cross_Ratio'), 20, now()),
    ('handle-rating:cross_ratio', 'handle-rating', jsonb_build_object('handle', 'Cross_Ratio'), 30, now()),
    ('handle-info:shadowdle', 'handle-info', jsonb_build_object('handle', 'Shadowdle'), 20, now()),
    ('handle-rating:shadowdle', 'handle-rating', jsonb_build_object('handle', 'Shadowdle'), 30, now()),
    ('handle-info:ashen-witch', 'handle-info', jsonb_build_object('handle', 'Ashen-Witch'), 20, now()),
    ('handle-rating:ashen-witch', 'handle-rating', jsonb_build_object('handle', 'Ashen-Witch'), 30, now()),
    ('handle-info:blackpink', 'handle-info', jsonb_build_object('handle', 'BLACKPINK'), 20, now()),
    ('handle-rating:blackpink', 'handle-rating', jsonb_build_object('handle', 'BLACKPINK'), 30, now()),
    ('handle-info:alsrjs0725', 'handle-info', jsonb_build_object('handle', 'alsrjs0725'), 20, now()),
    ('handle-rating:alsrjs0725', 'handle-rating', jsonb_build_object('handle', 'alsrjs0725'), 30, now()),
    ('handle-info:jaewonoh', 'handle-info', jsonb_build_object('handle', 'JaewonOh'), 20, now()),
    ('handle-rating:jaewonoh', 'handle-rating', jsonb_build_object('handle', 'JaewonOh'), 30, now()),
    ('handle-info:sch314', 'handle-info', jsonb_build_object('handle', 'SCH314'), 20, now()),
    ('handle-rating:sch314', 'handle-rating', jsonb_build_object('handle', 'SCH314'), 30, now()),
    ('handle-info:aaronkim00', 'handle-info', jsonb_build_object('handle', 'aaronkim00'), 20, now()),
    ('handle-rating:aaronkim00', 'handle-rating', jsonb_build_object('handle', 'aaronkim00'), 30, now()),
    ('handle-info:ssamt', 'handle-info', jsonb_build_object('handle', 'ssamt'), 20, now()),
    ('handle-rating:ssamt', 'handle-rating', jsonb_build_object('handle', 'ssamt'), 30, now()),
    ('handle-info:hanbyeol_', 'handle-info', jsonb_build_object('handle', 'hanbyeol_'), 20, now()),
    ('handle-rating:hanbyeol_', 'handle-rating', jsonb_build_object('handle', 'hanbyeol_'), 30, now()),
    ('handle-info:ez_code', 'handle-info', jsonb_build_object('handle', 'ez_code'), 20, now()),
    ('handle-rating:ez_code', 'handle-rating', jsonb_build_object('handle', 'ez_code'), 30, now()),
    ('handle-info:ai4youej', 'handle-info', jsonb_build_object('handle', 'ai4youej'), 20, now()),
    ('handle-rating:ai4youej', 'handle-rating', jsonb_build_object('handle', 'ai4youej'), 30, now()),
    ('handle-info:wizardrabbit', 'handle-info', jsonb_build_object('handle', 'wizardrabbit'), 20, now()),
    ('handle-rating:wizardrabbit', 'handle-rating', jsonb_build_object('handle', 'wizardrabbit'), 30, now()),
    ('handle-info:mz_en', 'handle-info', jsonb_build_object('handle', 'mz_en'), 20, now()),
    ('handle-rating:mz_en', 'handle-rating', jsonb_build_object('handle', 'mz_en'), 30, now()),
    ('handle-info:numbering', 'handle-info', jsonb_build_object('handle', 'Numbering'), 20, now()),
    ('handle-rating:numbering', 'handle-rating', jsonb_build_object('handle', 'Numbering'), 30, now()),
    ('handle-info:riroan', 'handle-info', jsonb_build_object('handle', 'riroan'), 20, now()),
    ('handle-rating:riroan', 'handle-rating', jsonb_build_object('handle', 'riroan'), 30, now()),
    ('handle-info:sorohue', 'handle-info', jsonb_build_object('handle', 'sorohue'), 20, now()),
    ('handle-rating:sorohue', 'handle-rating', jsonb_build_object('handle', 'sorohue'), 30, now()),
    ('handle-info:chromate00', 'handle-info', jsonb_build_object('handle', 'chromate00'), 20, now()),
    ('handle-rating:chromate00', 'handle-rating', jsonb_build_object('handle', 'chromate00'), 30, now()),
    ('handle-info:soongsil', 'handle-info', jsonb_build_object('handle', 'soongsil'), 20, now()),
    ('handle-rating:soongsil', 'handle-rating', jsonb_build_object('handle', 'soongsil'), 30, now()),
    ('handle-info:terrasphere', 'handle-info', jsonb_build_object('handle', 'terrasphere'), 20, now()),
    ('handle-rating:terrasphere', 'handle-rating', jsonb_build_object('handle', 'terrasphere'), 30, now()),
    ('handle-info:minpaper', 'handle-info', jsonb_build_object('handle', 'minpaper'), 20, now()),
    ('handle-rating:minpaper', 'handle-rating', jsonb_build_object('handle', 'minpaper'), 30, now()),
    ('handle-info:kleder', 'handle-info', jsonb_build_object('handle', 'Kleder'), 20, now()),
    ('handle-rating:kleder', 'handle-rating', jsonb_build_object('handle', 'Kleder'), 30, now()),
    ('handle-info:mythofys', 'handle-info', jsonb_build_object('handle', 'mythofys'), 20, now()),
    ('handle-rating:mythofys', 'handle-rating', jsonb_build_object('handle', 'mythofys'), 30, now()),
    ('handle-info:shinonome_ena', 'handle-info', jsonb_build_object('handle', 'Shinonome_Ena'), 20, now()),
    ('handle-rating:shinonome_ena', 'handle-rating', jsonb_build_object('handle', 'Shinonome_Ena'), 30, now()),
    ('handle-info:junah', 'handle-info', jsonb_build_object('handle', 'junah'), 20, now()),
    ('handle-rating:junah', 'handle-rating', jsonb_build_object('handle', 'junah'), 30, now()),
    ('handle-info:kaling', 'handle-info', jsonb_build_object('handle', 'Kaling'), 20, now()),
    ('handle-rating:kaling', 'handle-rating', jsonb_build_object('handle', 'Kaling'), 30, now()),
    ('handle-info:johnny8337', 'handle-info', jsonb_build_object('handle', 'johnny8337'), 20, now()),
    ('handle-rating:johnny8337', 'handle-rating', jsonb_build_object('handle', 'johnny8337'), 30, now()),
    ('handle-info:taeyun149', 'handle-info', jsonb_build_object('handle', 'taeyun149'), 20, now()),
    ('handle-rating:taeyun149', 'handle-rating', jsonb_build_object('handle', 'taeyun149'), 30, now()),
    ('handle-info:equinox_', 'handle-info', jsonb_build_object('handle', 'Equinox_'), 20, now()),
    ('handle-rating:equinox_', 'handle-rating', jsonb_build_object('handle', 'Equinox_'), 30, now()),
    ('handle-info:josephan8375', 'handle-info', jsonb_build_object('handle', 'josephan8375'), 20, now()),
    ('handle-rating:josephan8375', 'handle-rating', jsonb_build_object('handle', 'josephan8375'), 30, now()),
    ('handle-info:starbow_break', 'handle-info', jsonb_build_object('handle', 'Starbow_Break'), 20, now()),
    ('handle-rating:starbow_break', 'handle-rating', jsonb_build_object('handle', 'Starbow_Break'), 30, now()),
    ('handle-info:annyeong1', 'handle-info', jsonb_build_object('handle', 'annyeong1'), 20, now()),
    ('handle-rating:annyeong1', 'handle-rating', jsonb_build_object('handle', 'annyeong1'), 30, now()),
    ('handle-info:guroy', 'handle-info', jsonb_build_object('handle', 'guroy'), 20, now()),
    ('handle-rating:guroy', 'handle-rating', jsonb_build_object('handle', 'guroy'), 30, now()),
    ('handle-info:iccodly', 'handle-info', jsonb_build_object('handle', 'iccodly'), 20, now()),
    ('handle-rating:iccodly', 'handle-rating', jsonb_build_object('handle', 'iccodly'), 30, now()),
    ('handle-info:sshs22002', 'handle-info', jsonb_build_object('handle', 'sshs22002'), 20, now()),
    ('handle-rating:sshs22002', 'handle-rating', jsonb_build_object('handle', 'sshs22002'), 30, now()),
    ('handle-info:junha1282', 'handle-info', jsonb_build_object('handle', 'junha1282'), 20, now()),
    ('handle-rating:junha1282', 'handle-rating', jsonb_build_object('handle', 'junha1282'), 30, now()),
    ('handle-info:uuiip7878', 'handle-info', jsonb_build_object('handle', 'uuiip7878'), 20, now()),
    ('handle-rating:uuiip7878', 'handle-rating', jsonb_build_object('handle', 'uuiip7878'), 30, now()),
    ('handle-info:eltu815', 'handle-info', jsonb_build_object('handle', 'eltu815'), 20, now()),
    ('handle-rating:eltu815', 'handle-rating', jsonb_build_object('handle', 'eltu815'), 30, now()),
    ('handle-info:awwkje', 'handle-info', jsonb_build_object('handle', 'awwkje'), 20, now()),
    ('handle-rating:awwkje', 'handle-rating', jsonb_build_object('handle', 'awwkje'), 30, now()),
    ('handle-info:magicshow', 'handle-info', jsonb_build_object('handle', 'MagicShow'), 20, now()),
    ('handle-rating:magicshow', 'handle-rating', jsonb_build_object('handle', 'MagicShow'), 30, now()),
    ('handle-info:mbae059', 'handle-info', jsonb_build_object('handle', 'mbae059'), 20, now()),
    ('handle-rating:mbae059', 'handle-rating', jsonb_build_object('handle', 'mbae059'), 30, now()),
    ('handle-info:21007', 'handle-info', jsonb_build_object('handle', '21007'), 20, now()),
    ('handle-rating:21007', 'handle-rating', jsonb_build_object('handle', '21007'), 30, now()),
    ('handle-info:aaat', 'handle-info', jsonb_build_object('handle', 'aaat'), 20, now()),
    ('handle-rating:aaat', 'handle-rating', jsonb_build_object('handle', 'aaat'), 30, now()),
    ('handle-info:honeykill', 'handle-info', jsonb_build_object('handle', 'honeykill'), 20, now()),
    ('handle-rating:honeykill', 'handle-rating', jsonb_build_object('handle', 'honeykill'), 30, now()),
    ('handle-info:mingyu331', 'handle-info', jsonb_build_object('handle', 'Mingyu331'), 20, now()),
    ('handle-rating:mingyu331', 'handle-rating', jsonb_build_object('handle', 'Mingyu331'), 30, now()),
    ('handle-info:saturnalorbit', 'handle-info', jsonb_build_object('handle', 'Saturnalorbit'), 20, now()),
    ('handle-rating:saturnalorbit', 'handle-rating', jsonb_build_object('handle', 'Saturnalorbit'), 30, now()),
    ('handle-info:easteregg423', 'handle-info', jsonb_build_object('handle', 'easteregg423'), 20, now()),
    ('handle-rating:easteregg423', 'handle-rating', jsonb_build_object('handle', 'easteregg423'), 30, now()),
    ('handle-info:sshseddie', 'handle-info', jsonb_build_object('handle', 'sshseddie'), 20, now()),
    ('handle-rating:sshseddie', 'handle-rating', jsonb_build_object('handle', 'sshseddie'), 30, now()),
    ('handle-info:utilforever', 'handle-info', jsonb_build_object('handle', 'utilforever'), 20, now()),
    ('handle-rating:utilforever', 'handle-rating', jsonb_build_object('handle', 'utilforever'), 30, now()),
    ('handle-info:kongum', 'handle-info', jsonb_build_object('handle', 'kongum'), 20, now()),
    ('handle-rating:kongum', 'handle-rating', jsonb_build_object('handle', 'kongum'), 30, now()),
    ('handle-info:now_cow', 'handle-info', jsonb_build_object('handle', 'now_cow'), 20, now()),
    ('handle-rating:now_cow', 'handle-rating', jsonb_build_object('handle', 'now_cow'), 30, now()),
    ('handle-info:junhyung9985', 'handle-info', jsonb_build_object('handle', 'junhyung9985'), 20, now()),
    ('handle-rating:junhyung9985', 'handle-rating', jsonb_build_object('handle', 'junhyung9985'), 30, now()),
    ('handle-info:mickeyjung', 'handle-info', jsonb_build_object('handle', 'mickeyjung'), 20, now()),
    ('handle-rating:mickeyjung', 'handle-rating', jsonb_build_object('handle', 'mickeyjung'), 30, now()),
    ('handle-info:faruzan', 'handle-info', jsonb_build_object('handle', 'Faruzan'), 20, now()),
    ('handle-rating:faruzan', 'handle-rating', jsonb_build_object('handle', 'Faruzan'), 30, now()),
    ('handle-info:ogura_yui', 'handle-info', jsonb_build_object('handle', 'ogura_yui'), 20, now()),
    ('handle-rating:ogura_yui', 'handle-rating', jsonb_build_object('handle', 'ogura_yui'), 30, now()),
    ('handle-info:w8385', 'handle-info', jsonb_build_object('handle', 'w8385'), 20, now()),
    ('handle-rating:w8385', 'handle-rating', jsonb_build_object('handle', 'w8385'), 30, now()),
    ('handle-info:kaorin', 'handle-info', jsonb_build_object('handle', 'kaorin'), 20, now()),
    ('handle-rating:kaorin', 'handle-rating', jsonb_build_object('handle', 'kaorin'), 30, now()),
    ('handle-info:linzy_thanatos', 'handle-info', jsonb_build_object('handle', 'linzy_thanatos'), 20, now()),
    ('handle-rating:linzy_thanatos', 'handle-rating', jsonb_build_object('handle', 'linzy_thanatos'), 30, now()),
    ('handle-info:nflight11', 'handle-info', jsonb_build_object('handle', 'nflight11'), 20, now()),
    ('handle-rating:nflight11', 'handle-rating', jsonb_build_object('handle', 'nflight11'), 30, now()),
    ('handle-info:cygnus_330', 'handle-info', jsonb_build_object('handle', 'cygnus_330'), 20, now()),
    ('handle-rating:cygnus_330', 'handle-rating', jsonb_build_object('handle', 'cygnus_330'), 30, now()),
    ('handle-info:sjh1224', 'handle-info', jsonb_build_object('handle', 'sjh1224'), 20, now()),
    ('handle-rating:sjh1224', 'handle-rating', jsonb_build_object('handle', 'sjh1224'), 30, now()),
    ('handle-info:blackkarn', 'handle-info', jsonb_build_object('handle', 'blackkarn'), 20, now()),
    ('handle-rating:blackkarn', 'handle-rating', jsonb_build_object('handle', 'blackkarn'), 30, now()),
    ('handle-info:invrtd.h', 'handle-info', jsonb_build_object('handle', 'invrtd.h'), 20, now()),
    ('handle-rating:invrtd.h', 'handle-rating', jsonb_build_object('handle', 'invrtd.h'), 30, now()),
    ('handle-info:schur', 'handle-info', jsonb_build_object('handle', 'Schur'), 20, now()),
    ('handle-rating:schur', 'handle-rating', jsonb_build_object('handle', 'Schur'), 30, now()),
    ('handle-info:iktk', 'handle-info', jsonb_build_object('handle', 'iktk'), 20, now()),
    ('handle-rating:iktk', 'handle-rating', jsonb_build_object('handle', 'iktk'), 30, now()),
    ('handle-info:cologne1723', 'handle-info', jsonb_build_object('handle', 'cologne1723'), 20, now()),
    ('handle-rating:cologne1723', 'handle-rating', jsonb_build_object('handle', 'cologne1723'), 30, now()),
    ('handle-info:chiyo_shock', 'handle-info', jsonb_build_object('handle', 'chiyo_shock'), 20, now()),
    ('handle-rating:chiyo_shock', 'handle-rating', jsonb_build_object('handle', 'chiyo_shock'), 30, now()),
    ('handle-info:toycartoon', 'handle-info', jsonb_build_object('handle', 'toycartoon'), 20, now()),
    ('handle-rating:toycartoon', 'handle-rating', jsonb_build_object('handle', 'toycartoon'), 30, now()),
    ('handle-info:iacobus', 'handle-info', jsonb_build_object('handle', 'iacobus'), 20, now()),
    ('handle-rating:iacobus', 'handle-rating', jsonb_build_object('handle', 'iacobus'), 30, now()),
    ('handle-info:prettychang', 'handle-info', jsonb_build_object('handle', 'prettychang'), 20, now()),
    ('handle-rating:prettychang', 'handle-rating', jsonb_build_object('handle', 'prettychang'), 30, now()),
    ('handle-info:undertaker', 'handle-info', jsonb_build_object('handle', 'UNDERTAKER'), 20, now()),
    ('handle-rating:undertaker', 'handle-rating', jsonb_build_object('handle', 'UNDERTAKER'), 30, now()),
    ('handle-info:woohyun_jng', 'handle-info', jsonb_build_object('handle', 'woohyun_jng'), 20, now()),
    ('handle-rating:woohyun_jng', 'handle-rating', jsonb_build_object('handle', 'woohyun_jng'), 30, now()),
    ('handle-info:synthes1s', 'handle-info', jsonb_build_object('handle', 'synthes1s'), 20, now()),
    ('handle-rating:synthes1s', 'handle-rating', jsonb_build_object('handle', 'synthes1s'), 30, now()),
    ('handle-info:kdy8128', 'handle-info', jsonb_build_object('handle', 'kdy8128'), 20, now()),
    ('handle-rating:kdy8128', 'handle-rating', jsonb_build_object('handle', 'kdy8128'), 30, now()),
    ('handle-info:khf7000', 'handle-info', jsonb_build_object('handle', 'khf7000'), 20, now()),
    ('handle-rating:khf7000', 'handle-rating', jsonb_build_object('handle', 'khf7000'), 30, now()),
    ('handle-info:angeliayam', 'handle-info', jsonb_build_object('handle', 'angeliayam'), 20, now()),
    ('handle-rating:angeliayam', 'handle-rating', jsonb_build_object('handle', 'angeliayam'), 30, now()),
    ('handle-info:hello107', 'handle-info', jsonb_build_object('handle', 'hello107'), 20, now()),
    ('handle-rating:hello107', 'handle-rating', jsonb_build_object('handle', 'hello107'), 30, now()),
    ('handle-info:lemonoyaa', 'handle-info', jsonb_build_object('handle', 'lemonoyaa'), 20, now()),
    ('handle-rating:lemonoyaa', 'handle-rating', jsonb_build_object('handle', 'lemonoyaa'), 30, now()),
    ('handle-info:bsh1004', 'handle-info', jsonb_build_object('handle', 'bsh1004'), 20, now()),
    ('handle-rating:bsh1004', 'handle-rating', jsonb_build_object('handle', 'bsh1004'), 30, now()),
    ('handle-info:kohada', 'handle-info', jsonb_build_object('handle', 'kohada'), 20, now()),
    ('handle-rating:kohada', 'handle-rating', jsonb_build_object('handle', 'kohada'), 30, now()),
    ('handle-info:iluem100', 'handle-info', jsonb_build_object('handle', 'iluem100'), 20, now()),
    ('handle-rating:iluem100', 'handle-rating', jsonb_build_object('handle', 'iluem100'), 30, now()),
    ('handle-info:kolorvxl', 'handle-info', jsonb_build_object('handle', 'kolorVXL'), 20, now()),
    ('handle-rating:kolorvxl', 'handle-rating', jsonb_build_object('handle', 'kolorVXL'), 30, now()),
    ('handle-info:cywohoy', 'handle-info', jsonb_build_object('handle', 'cywohoy'), 20, now()),
    ('handle-rating:cywohoy', 'handle-rating', jsonb_build_object('handle', 'cywohoy'), 30, now()),
    ('handle-info:seer_of_c', 'handle-info', jsonb_build_object('handle', 'seer_of_c'), 20, now()),
    ('handle-rating:seer_of_c', 'handle-rating', jsonb_build_object('handle', 'seer_of_c'), 30, now()),
    ('handle-info:sb_p_0x7', 'handle-info', jsonb_build_object('handle', 'sb_p_0x7'), 20, now()),
    ('handle-rating:sb_p_0x7', 'handle-rating', jsonb_build_object('handle', 'sb_p_0x7'), 30, now()),
    ('handle-info:notkim16', 'handle-info', jsonb_build_object('handle', 'notkim16'), 20, now()),
    ('handle-rating:notkim16', 'handle-rating', jsonb_build_object('handle', 'notkim16'), 30, now()),
    ('handle-info:hakuaa_2', 'handle-info', jsonb_build_object('handle', 'Hakuaa_2'), 20, now()),
    ('handle-rating:hakuaa_2', 'handle-rating', jsonb_build_object('handle', 'Hakuaa_2'), 30, now()),
    ('handle-info:lumitt', 'handle-info', jsonb_build_object('handle', 'lumitt'), 20, now()),
    ('handle-rating:lumitt', 'handle-rating', jsonb_build_object('handle', 'lumitt'), 30, now()),
    ('handle-info:cenix820', 'handle-info', jsonb_build_object('handle', 'Cenix820'), 20, now()),
    ('handle-rating:cenix820', 'handle-rating', jsonb_build_object('handle', 'Cenix820'), 30, now()),
    ('handle-info:_______________________', 'handle-info', jsonb_build_object('handle', '_______________________'), 20, now()),
    ('handle-rating:_______________________', 'handle-rating', jsonb_build_object('handle', '_______________________'), 30, now()),
    ('handle-info:cy4n1de', 'handle-info', jsonb_build_object('handle', 'cy4n1de'), 20, now()),
    ('handle-rating:cy4n1de', 'handle-rating', jsonb_build_object('handle', 'cy4n1de'), 30, now()),
    ('handle-info:kokiri', 'handle-info', jsonb_build_object('handle', 'kokiri'), 20, now()),
    ('handle-rating:kokiri', 'handle-rating', jsonb_build_object('handle', 'kokiri'), 30, now()),
    ('handle-info:kulkuri', 'handle-info', jsonb_build_object('handle', 'kulkuri'), 20, now()),
    ('handle-rating:kulkuri', 'handle-rating', jsonb_build_object('handle', 'kulkuri'), 30, now()),
    ('handle-info:qwertyuiojhygtfdfg', 'handle-info', jsonb_build_object('handle', 'qwertyuiojhygtfdfg'), 20, now()),
    ('handle-rating:qwertyuiojhygtfdfg', 'handle-rating', jsonb_build_object('handle', 'qwertyuiojhygtfdfg'), 30, now())
on conflict (task_key) do update set
  task_type = excluded.task_type,
  payload = excluded.payload,
  priority = least(public.cf_cache_warm_queue.priority, excluded.priority),
  run_after = least(public.cf_cache_warm_queue.run_after, excluded.run_after),
  done_at = null,
  locked_at = null,
  last_error = null,
  updated_at = now();

comment on table public.cf_performance_estimates is
  'Compact Codeforces Lab performance points derived from contest.ratingChanges.';

comment on table public.cf_cache_warm_queue is
  'Bounded background queue for prewarming Codeforces Lab normalized cache.';
